const ACCOUNT_STATUS = {
  PENDING: "PENDING",
  ACTIVE: "ACTIVE",
  LOCKED: "LOCKED",
  DISABLED: "DISABLED",
  DELETED: "DELETED",
};

const STUDENT_STATUS = {
  INCOMPLETE: "INCOMPLETE",
  ACTIVE: "ACTIVE",
  SUSPENDED: "SUSPENDED",
  GRADUATED: "GRADUATED",
  WITHDRAWN: "WITHDRAWN",
};

const INSTRUCTOR_STATUS = {
  PROBATION: "PROBATION",
  ACTIVE: "ACTIVE",
  SUSPENDED: "SUSPENDED",
  ON_LEAVE: "ON_LEAVE",
  TERMINATED: "TERMINATED",
};

const COURSE_STATUS = {
  PENDING: "PENDING",
  ACTIVE: "ACTIVE",
  LOCKED: "LOCKED",
  DISABLED: "DISABLED",
  DELETED: "DELETED",
};

const CLASS_STATUS = {
  PENDING: "PENDING",
  OPEN_REGISTRATION: "OPEN_REGISTRATION",
  ONGOING: "ONGOING",
  COMPLETED: "COMPLETED",
  DELETED: "DELETED",
};

const ENROLLMENT_STATUS = {
  PENDING: "PENDING",
  WAITING_FOR_PAYMENT: "WAITING_FOR_PAYMENT",
  CONFIRMED: "CONFIRMED",
  CANCELLED: "CANCELLED",
  REFUNDED: "REFUNDED",
};

const ROOM_STATUS = {
  AVAILABLE: "AVAILABLE",
  MAINTENANCE: "MAINTENANCE",
};

const ATTENDANCE_STATUS = {
  PRESENT: "PRESENT",
  ABSENT: "ABSENT",
  LATE: "LATE",
  EXCUSED: "EXCUSED",
};

const GRADE_STATUS = {
  DRAFT: "DRAFT",
  PUBLISHED: "PUBLISHED",
  LOCKED: "LOCKED",
};

const DOCUMENT_STATUS = {
  AVAILABLE: "AVAILABLE",
  ARCHIVED: "ARCHIVED",
  DELETED: "DELETED",
};

const PAYMENT_STATUS = {
  UNPAID: "UNPAID",
  PARTIALLY_PAID: "PARTIALLY_PAID",
  FULLY_PAID: "FULLY_PAID",
  FAILED: "FAILED",
  REFUNDED: "REFUNDED",
};

const CERTIFICATE_STATUS = {
  ISSUED: "ISSUED",
  REVOKED: "REVOKED",
};

module.exports = {
  ACCOUNT_STATUS,
  STUDENT_STATUS,
  INSTRUCTOR_STATUS,
  COURSE_STATUS,
  CLASS_STATUS,
  ENROLLMENT_STATUS,
  ROOM_STATUS,
  ATTENDANCE_STATUS,
  GRADE_STATUS,
  DOCUMENT_STATUS,
  PAYMENT_STATUS,
  CERTIFICATE_STATUS,
};