import { ERROR_CODES } from "@/constants";

export const VALIDATION_ERROR_MAP = {
  required: ERROR_CODES.REQUIRED_FIELD,
  email: ERROR_CODES.INVALID_EMAIL,
  phone: ERROR_CODES.INVALID_PHONE,
  minLength: ERROR_CODES.MIN_LENGTH,
  maxLength: ERROR_CODES.MAX_LENGTH,
  pattern: ERROR_CODES.INVALID_PATTERN,
  strongPassword: ERROR_CODES.WEAK_PASSWORD,
  pastDate: ERROR_CODES.PAST_DATE_REQUIRED,
  futureDate: ERROR_CODES.FUTURE_DATE_REQUIRED,
};
