USE training_management;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS ATTENDANCE;
DROP TABLE IF EXISTS CERTIFICATE;
DROP TABLE IF EXISTS PAYMENT;
DROP TABLE IF EXISTS GRADE;
DROP TABLE IF EXISTS DOCUMENT;
DROP TABLE IF EXISTS SCHEDULE;
DROP TABLE IF EXISTS ROOM;
DROP TABLE IF EXISTS ENROLLMENT;
DROP TABLE IF EXISTS REGISTRATION;
DROP TABLE IF EXISTS STUDENT;
DROP TABLE IF EXISTS CLASS;
DROP TABLE IF EXISTS STAFF_CAPABILITY;
DROP TABLE IF EXISTS STAFF_DEPARTMENT;
DROP TABLE IF EXISTS COURSE;
DROP TABLE IF EXISTS DEPARTMENT;
DROP TABLE IF EXISTS STAFF_PROFILE;
DROP TABLE IF EXISTS USER_ROLE;
DROP TABLE IF EXISTS ACCOUNT;
DROP TABLE IF EXISTS ROLE;

SET FOREIGN_KEY_CHECKS = 1;

SHOW TABLES;